FROM debian:11-slim AS builder
RUN apt-get update -y
RUN apt-get install -y python3 python3-pip

FROM builder as final
ENV PYTHONBUFFERED 1
RUN mkdir /tmp/code
ADD ./ /tmp/code
WORKDIR /tmp/code

RUN python3 -m pip install -U pip \
    && python3 -m pip install -r requirements-build.txt \
    && python3 -m pip install .
